### ISSUE TITLE
osu!Stats crashes on undefined users

### ISSUE THREAD

**Issue by sr229** [owo-dev-team/owo-whats-this#24]
Stacktrace : 

```
C:\Users\Krystal\Documents\owo-whats-this\out\commands\awwwsooo\osu.js:34
                    if (user.user_id == undefined) {
                            ^

TypeError: Cannot read property 'user_id' of undefined
    at IncomingMessage.<anonymous> (C:\Users\Krystal\Documents\owo-whats-this\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by Ovyerus** [comment]
Fixed in #21

**Comment by sr229** [comment]
Issue still persists on public bot. Reopening

**Comment by sr229** [comment]
Re-Closing, Issue might have been fixed now
