### ISSUE TITLE
Symbol iterator is somehow undefined

### ISSUE THREAD

**Issue by sr229** [owo-dev-team/owo-whats-this#32]
## Error type
TypeError

## Summary
```prolog

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```
## Stacktrace

```prolog
   at err (C:\Users\Krystal\Documents\owo-whats-this\src\lib\commandLoader.js:43:24
   at new Promise (C:\Users\Krystal\Documents\owo-whats-this\node_modules\bluebird\js\release\promise.js:77:14)
    at preloadCommands (C:\Users\Krystal\Documents\owo-whats-this\src\lib\commandLoader.js:41:12)
    at Promise (C:\Users\Krystal\Documents\owo-whats-this\src\lib\commandLoader.js:111:9)
    at Promise._execute (C:\Users\Krystal\Documents\owo-whats-this\node_modules\bluebird\js\release\debuggability.js:299:9)
    at Promise._resolveFromExecutor (C:\Users\Krystal\Documents\owo-whats-this\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Users\Krystal\Documents\owo-whats-this\node_modules\bluebird\js\release\promise.js:77:14)
    at Object.exports.init (C:\Users\Krystal\Documents\owo-whats-this\src\lib\commandLoader.js:109:12)
    at Client.bot.on (C:\Users\Krystal\Documents\owo-whats-this\src\bot.js:77:50)
    at emitNone (events.js:91:20)
    at Client.emit (events.js:185:7)
    at WebSocketManager._emitReady (C:\Users\Krystal\Documents\owo-whats-this\node_modules\discord.js\src\client\websocket\WebSocketManager.js:221:17)
    at WebSocketManager.checkIfReady (C:\Users\Krystal\Documents\owo-whats-this\node_modules\discord.js\src\client\websocket\WebSocketManager.js:246:14)
    at GuildCreateHandler.handle (C:\Users\Krystal\Documents\owo-whats-this\node_modules\discord.js\src\client\websocket\packets\handlers\GuildCreate.js:13:31)```

**Comment by Ovyerus** [comment]
Fixed in #21
